In [1]:
import numpy as np

In [5]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
v[1]

3

In [8]:
[v[1],v[3]]

[3, 9]

In [9]:
bring=[1,3,7]

In [10]:
v[bring]

array([ 3,  9, 21])

In [11]:
#iki boyutta Fancy

In [13]:
j=np.arange(9).reshape((3,3))

In [14]:
j

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
sat=np.array([1,2])
sut=np.array([1,2])

In [21]:
j[sat,sut]

array([4, 8])

In [22]:
#basit index le fancy

In [26]:
j

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
j[0,[1,2]]  #array içinde array cagırıyoruz aslında

array([1, 2])

In [29]:
#Kosullu Eleman

In [31]:
import numpy as np
c=np.array([1,2,3,4])

In [33]:
c<3 #her eleman icin

array([ True,  True, False, False])

In [35]:
c[c>3] #fancy ile kosulluyu getir

array([4])

In [36]:
c[c>=0]

array([1, 2, 3, 4])

In [ ]:
#kosulları icinde cagırıyoruz 

In [37]:
c*2

array([2, 4, 6, 8])

In [38]:
c*5/10

array([0.5, 1. , 1.5, 2. ])

In [39]:
v**5

array([       0,      243,     7776,    59049,   248832,   759375,
        1889568,  4084101,  7962624, 14348907], dtype=int32)

In [40]:
#matematiksel islemler

In [42]:
import numpy as np
f=np.array([1,2,3,4,5])

In [45]:
f

array([1, 2, 3, 4, 5])

In [46]:
f*5

array([ 5, 10, 15, 20, 25])

In [48]:
#ufunc calsııyor....

In [49]:
np.subtract(f,1)

array([0, 1, 2, 3, 4])

In [51]:
np.add(f,1)

array([2, 3, 4, 5, 6])

In [52]:
np.multiply(f,2)

array([ 2,  4,  6,  8, 10])

In [53]:
v**3

array([    0,    27,   216,   729,  1728,  3375,  5832,  9261, 13824,
       19683], dtype=int32)

In [54]:
v%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [56]:
np.absolute(v) #mutlakdeger fonk

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [57]:
np.sin(60)

-0.3048106211022167

In [58]:
np.cos(-92)

-0.626444447910339

In [59]:
u=np.array([1,2,3,4])

In [61]:
np.log(u)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [66]:
?np

In [67]:
  #ana dokumentasyon

In [68]:
f.min()

1

In [44]:
#iki bilinmeyenli denklem

In [69]:
import numpy as np

In [79]:
a=np.array([[5,1],[1,3]])
b=np.array([12,10])

In [82]:
x=np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

In [85]:

a=np.array([[4, 0, 3, 0, 1],

            [9, 6, 1, 5, 9],

            [1, 9, 0, 8, 2]])




a[0:1]

array([[4, 0, 3, 0, 1]])