In [262]:
import numpy as np

In [263]:
a=np.array([1,2,3,4])

In [264]:
type(a)  #fixed type

numpy.ndarray

In [265]:
np.array([3.14,4.34,2.23 ],dtype="float32")  #float var veya int var

array([3.14, 4.34, 2.23], dtype=float32)

In [266]:
#sıfırdan array olusturma


In [267]:
np.zeros(10)  #dtypedan yine degistirebiliriz.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [268]:
np.ones([4,2])  #1lerden olusan array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [269]:
np.full([2,4],5)  #ici beslerden olussun


array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [270]:
np.arange(0,45,6) #45e kadar 6sar artan 

array([ 0,  6, 12, 18, 24, 30, 36, 42])

In [271]:
np.linspace(0,10,6)  #0 10 arsı 6

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [272]:
np.random.normal(10,4,(6,2))  #normal dagılımm

array([[ 4.78734658,  8.07670037],
       [12.01386992, 15.48856335],
       [12.0959001 , 11.2230696 ],
       [ 7.58842972, 10.27448303],
       [15.83561815,  7.96481857],
       [ 4.21436843, 14.72252362]])

In [273]:
np.random.randint(0,10,(3,4))

array([[2, 0, 5, 1],
       [2, 0, 4, 8],
       [2, 8, 7, 5]])

In [274]:
#Features

* ndim:boyut
* shape:boyut bilgisi
* size toplam eleman
* dtype tipi

In [275]:
import numpy as np

In [276]:
a=np.random.randint(10,size=(2))

In [277]:
a.ndim

1

In [278]:
a.shape  #satır sutun bilgisi 

(2,)

In [279]:
a.size  #boyut bilgisi 

2

In [280]:
a.dtype

dtype('int32')

In [281]:
b= np.random.randint(10,size=(10,2))  #10x2 matris   #10sutun 2 satır

In [282]:
b

array([[7, 7],
       [8, 7],
       [9, 1],
       [5, 6],
       [0, 5],
       [7, 2],
       [5, 1],
       [4, 7],
       [0, 5],
       [0, 7]])

In [283]:
b.ndim

2

In [284]:
b.shape

(10, 2)

In [285]:
b.size

20

## reshaping

In [286]:
import numpy as np

In [287]:
np.arange(1,10)  #3x3e donstlm

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [288]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [289]:
a=np.arange(1,10) #vektor

In [290]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [291]:
a.ndim

1

In [292]:
b=a.reshape((1,9)) #artık matristir boyutu ikidir

In [293]:
b.ndim

2

## concatanete

In [294]:
import numpy as np

In [295]:
x=np.array([1,2,3,5])
y=np.array([9,2,7,6])

In [296]:
np.concatenate([x,y])

array([1, 2, 3, 5, 9, 2, 7, 6])

In [297]:
z=np.array([12,455,5])

In [298]:
np.concatenate([x,y,z])

array([  1,   2,   3,   5,   9,   2,   7,   6,  12, 455,   5])

In [299]:
#İki boyut

In [300]:
v= np.array([[1,2,23],
     [1,2,38]])

In [301]:
np.concatenate([v,v])  #satır birlestirme

array([[ 1,  2, 23],
       [ 1,  2, 38],
       [ 1,  2, 23],
       [ 1,  2, 38]])

In [302]:
np.concatenate([v,v], axis=1)  #sutun birleştirmw

array([[ 1,  2, 23,  1,  2, 23],
       [ 1,  2, 38,  1,  2, 38]])

## SPLITTING

In [303]:
import numpy as np

In [304]:
x=np.array([1,2,3,99,56])

In [305]:
np.split(x,[0,3])

[array([], dtype=int32), array([1, 2, 3]), array([99, 56])]

In [109]:
a,b,c=np.split(x,[0,3])

In [110]:
c

array([99, 56])

In [112]:
#iki boyutlu

In [113]:
m=np.arange(16).reshape(4,4)

In [114]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [116]:
ust,alt=np.vsplit(m,[2])

In [117]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [118]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

## Sorting

In [119]:
import numpy as np

In [120]:
a=np.array([1,3,2435])

In [122]:
np.sort(a)

array([   1,    3, 2435])

In [124]:
a

array([   1,    3, 2435])

In [129]:
a.sort() #yapıyı bozdu

In [130]:
a

array([   1,    3, 2435])

In [131]:
#iki boyutlu

In [141]:
p=np.random.normal(20,5,(3,3))

In [142]:
np.sort(p) #satırlara gore

array([[23.35685001, 27.45611424, 27.77677563],
       [17.63037267, 21.08959117, 27.67020014],
       [11.02651223, 11.30029609, 28.97100446]])

In [143]:
np.sort(p,axis=1)   #satırlar

array([[23.35685001, 27.45611424, 27.77677563],
       [17.63037267, 21.08959117, 27.67020014],
       [11.02651223, 11.30029609, 28.97100446]])

In [145]:
np.sort(p,axis=0) #sutunlar

array([[23.35685001, 11.02651223, 11.30029609],
       [27.67020014, 17.63037267, 21.08959117],
       [28.97100446, 27.45611424, 27.77677563]])

## Eleman İslemleri

In [147]:
#indexle elemanlara erismek

In [150]:
import numpy as np
a=np.random.randint(10,size=10)
a


array([7, 8, 4, 5, 1, 5, 4, 0, 0, 4])

In [151]:
a[0]

7

In [152]:
a[5]

5

In [153]:
a[4]=180

In [155]:
a

array([  7,   8,   4,   5, 180,   5,   4,   0,   0,   4])

In [161]:
u=np.random.randint(10,size=(2,2))  #10'a kadar random atıyor

In [171]:
u

array([[7, 2],
       [8, 7]])

In [172]:
u[0,0]

7

In [174]:
u[0,1]=77


In [175]:
u

array([[ 7, 77],
       [ 8,  7]])

In [176]:
#float verince ondalık yapıyor.

In [148]:
#array alt kume

In [178]:
import numpy as np
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [179]:
a[0:4]

array([10, 11, 12, 13])

In [180]:
a[5:]

array([15, 16, 17, 18, 19])

In [181]:
a[0::2]

array([10, 12, 14, 16, 18])

In [182]:
#iki boyutlu slice

In [201]:
m=np.random.randint(10,size=(6,6))

In [202]:
m

array([[1, 3, 5, 6, 2, 2],
       [8, 2, 4, 0, 4, 0],
       [1, 9, 3, 5, 0, 0],
       [9, 4, 8, 0, 8, 6],
       [5, 3, 5, 8, 3, 1],
       [2, 8, 7, 3, 2, 6]])

In [203]:
m[:,0]  #ilk sutun

array([1, 8, 1, 9, 5, 2])

In [204]:
 m[0,:] #satır

array([1, 3, 5, 6, 2, 2])

In [205]:
m[0:2,0:3] #2.satır 3.sutun 

array([[1, 3, 5],
       [8, 2, 4]])

In [206]:
m

array([[1, 3, 5, 6, 2, 2],
       [8, 2, 4, 0, 4, 0],
       [1, 9, 3, 5, 0, 0],
       [9, 4, 8, 0, 8, 6],
       [5, 3, 5, 8, 3, 1],
       [2, 8, 7, 3, 2, 6]])

In [208]:
m[::] #hepsini AL

array([[1, 3, 5, 6, 2, 2],
       [8, 2, 4, 0, 4, 0],
       [1, 9, 3, 5, 0, 0],
       [9, 4, 8, 0, 8, 6],
       [5, 3, 5, 8, 3, 1],
       [2, 8, 7, 3, 2, 6]])

In [200]:
#alt kume üstünde islem

In [209]:
import numpy as np

In [212]:
a=np.random.randint(10,size=(5,5))
a

array([[1, 1, 2, 4, 8],
       [4, 7, 2, 3, 4],
       [5, 8, 4, 4, 4],
       [5, 1, 3, 6, 8],
       [9, 4, 9, 8, 4]])

In [214]:
alt=a[0:2,0:3]  
alt

array([[1, 1, 2],
       [4, 7, 2]])

In [ ]:
 #alt kumede yapılan degisim ana arrayi bozuyor

In [215]:
alt[0,0]=999

In [216]:
alt


array([[999,   1,   2],
       [  4,   7,   2]])

In [217]:
a

array([[999,   1,   2,   4,   8],
       [  4,   7,   2,   3,   4],
       [  5,   8,   4,   4,   4],
       [  5,   1,   3,   6,   8],
       [  9,   4,   9,   8,   4]])

In [223]:
alt_b=a[0:2,0:3].copy()

In [224]:
alt_b

array([[999,   1,   2],
       [  4,   7,   2]])

In [227]:
alt_b[0,0]=7777
alt_b

array([[7777,    1,    2],
       [   4,    7,    2]])

In [306]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [307]:
#Yani alt array yaparken copy metodu kullanmak yeni deger atarken ilk arrayi bozmaz

## EK 

In [321]:
import numpy as np

a=np.arange(0,10, 2)  #for dongusu gibi dusun!!!

In [313]:
a

array([0, 2, 4, 6, 8])

In [323]:
import numpy as np
5*np.array([1,2,3])  #DOGRUDUR!

array([ 5, 10, 15])